DROP TABLE IF EXISTS users     cascade;
DROP TABLE IF EXISTS category  cascade;
DROP TABLE IF EXISTS locations cascade;
DROP TABLE IF EXISTS events    cascade;

CREATE TABLE IF NOT EXISTS users (
  id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(250) NOT NULL UNIQUE,
  name  VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
  id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
  id  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat DOUBLE NOT NULL,
  lon DOUBLE NOT NULL,
);

CREATE TABLE IF NOT EXISTS events (
  id                 BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              VARCHAR(120)                NOT NULL,
  annotation         VARCHAR(2000)               NOT NULL,
  description        VARCHAR(7000)               NOT NULL,
  state              VARCHAR(20)                 NOT NULL,
  is_paid            BOOLEAN                     NOT NULL,
  category_id        BIGINT                      NOT NULL REFERENCES category (id) ON DELETE CASCADE ON UPDATE CASCADE,
  location_id        BIGINT                      NOT NULL REFERENCES locations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id            BIGINT                      NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  published_date     TIMESTAMP WITHOUT TIME ZONE,
  event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  limit              INTEGER                     NOT NULL,
  confirmed_requests INTEGER DEFAULT 0,
  request_moderation BOOLEAN                     NOT NULL,
  views              INTEGER DEFAULT 0
);




DROP TABLE IF EXISTS bookings cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS comments cascade;


CREATE TABLE IF NOT EXISTS requests (
  id           BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description  VARCHAR(500)                NOT NULL,
  created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  requestor_id BIGINT                      NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(50) NOT NULL,
  description  VARCHAR(500) NOT NULL,
  is_available BOOLEAN      NOT NULL,
  owner_id     BIGINT       NOT NULL REFERENCES users (id)   ON DELETE CASCADE ON UPDATE CASCADE,
  request_id   BIGINT                REFERENCES requests (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id         BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  status     VARCHAR(20)                 NOT NULL,
  item_id    BIGINT                      NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
  booker_id  BIGINT                      NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS comments (
  id           BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text         VARCHAR(500)                NOT NULL,
  created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id      BIGINT                      NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
  author_id    BIGINT                      NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);