version: '3.1'

services:
  stats-server:
    build: stats-service/server
    image: image-stats-server
    container_name: container-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=owner
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6551:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=root

  main-service:
    build: main-service
    image: image-main
    container_name: container-main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db


  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=root